# .github/workflows/deploy.yml
name: deploy to deta space

on: 
  push:
    branches:
    - main

jobs:
  deploy:
    name: deploy to deta space
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      uses: lizheming/deta-action@master
      with:
        access_token: ${{ secrets.ACCESS_TOKEN }}
        id: ${{ secrets.PROJECT_ID }}
        version: "1.0.0"
        notes: "Release automatically with GitHub deta action"
        listed: true